#!/bin/sh

set -eu

if [ $# != 1 ] ; then
	echo usage: $0 '<suffix>'
	exit 1
fi

# the SUFFIX must not contain spaces or shell meta characters
SUFFIX=$1

if [ -e /etc/apache22deb-$SUFFIX ] ; then
	echo ERROR: /etc/apache22deb-$SUFFIX already exists
	exit 2
fi

echo Setting up /etc/apache22deb-$SUFFIX ...
cp -a /etc/apache22deb /etc/apache22deb-$SUFFIX

echo Setting up /etc/rc.d/init.d/apache22deb-$SUFFIX ...
cp /usr/share/doc/apache22deb/examples/secondary-init-script /etc/rc.d/init.d/apache22deb-$SUFFIX
# adjust service name (this prevents us from using a simple symlink)
perl -p -i -e s,XXX,$SUFFIX, /etc/rc.d/init.d/apache22deb-$SUFFIX
chmod 755 /etc/rc.d/init.d/apache22deb-$SUFFIX

echo -n Setting up symlinks: 
for a in a2enmod a2dismod a2ensite a2dissite apache22debctl ; do
	echo -n " $a-$SUFFIX"
	ln -s /usr/sbin/$a /usr/local/sbin/$a-$SUFFIX
done
echo

echo Setting up /etc/logrotate.d/apache22deb-$SUFFIX and /var/log/apache22deb-$SUFFIX ...
cp -a /etc/logrotate.d/apache22deb /etc/logrotate.d/apache22deb-$SUFFIX
perl -p -i -e s,apache22deb,apache22deb-$SUFFIX,g /etc/logrotate.d/apache22deb-$SUFFIX
mkdir /var/log/apache22deb-$SUFFIX
chmod 750 /var/log/apache22deb-$SUFFIX
chown root:root /var/log/apache22deb-$SUFFIX
