#!/bin/sh

# run htcacheclean

set -e
set -u

[ -e /usr/sbin/htcacheclean ] || exit 0
[ -e /etc/sysconfig/apache22deb ]   || exit 0


# edit /etc/sysconfig/apache22deb to change this
HTCACHECLEAN_MODE=daemon
HTCACHECLEAN_RUN=auto
HTCACHECLEAN_SIZE=300M
HTCACHECLEAN_PATH=/var/cache/apache22deb/mod_disk_cache
HTCACHECLEAN_OPTIONS=""

. /etc/sysconfig/apache22deb

[ "$HTCACHECLEAN_MODE" = "cron" ] || exit 0

[ "$HTCACHECLEAN_RUN" = "yes"	] || 
( [ "$HTCACHECLEAN_RUN" = "auto" ] && \
  [ -e /etc/apache22deb/mods-enabled/disk_cache.load ] )  || exit 0

/usr/sbin/htcacheclean  ${HTCACHECLEAN_OPTIONS}	\
			-p${HTCACHECLEAN_PATH}	\
			-l${HTCACHECLEAN_SIZE}

